### ISSUE TITLE
Wiki fails to dump

### ISSUE THREAD

**Issue by retro-mouse** [saveweb/wikiteam3#6]
I can't tell what is wrong with the tool or the site, it gets the page list but fails to download the pages:
```
dumpgenerator https://www.ff6hacking.com/ff5wiki/index.php/Main_Page --xml --images
```

**Comment by yzqzss** [comment]
I guess maybe ~~the URL rewriting rules for index.php on this wiki are a bit special~~. I've turned off my computer, so I'll look into it tomorrow.

---

You can use `--xmlapiexport` .

```shell
dumpgenerator https://www.ff6hacking.com/ff5wiki/index.php/Main_Page --xml --xmlapiexport --images
```

**Comment by yzqzss** [comment]
This wiki's `Specia:Export` is weird. If more than two revisions are exported, the `</page>` in the output xml will be removed.

![screen_shot](https://user-images.githubusercontent.com/30341059/232456632-bbbb8b4b-7e91-4545-a950-5e30df498004.png)

**Comment by yzqzss** [comment]
Uploaded with `--xml --xmlapiexport --images`:

<https://archive.org/details/wiki-ff6hackingcom_ff5wiki-20230417>

**Comment by retro-mouse** [comment]
Thanks for the export!
I wonder why it does that. I guess nothing to do about this then.

**Comment by Pokechu22** [comment]
See [T207974](https://phabricator.wikimedia.org/T207974). This also affects https://wiki.calafou.org (MW 1.32.1), but only when POSTing to e.g. `https://wiki.calafou.org/index.php?action=submit&offset=1&limit=1000&pages=%27%27%27_mapas_de_flujos%27%27%27&title=Special%3AExport` with no request body, not when POSTing to `https://wiki.calafou.org/index.php/Special:Export` (including when using Special:Export in a browser).

Python 2 WikiTeam's `--xmlrevisions` dumped everything successfully for that site, though it produced 3744 revisions while Special:Statistics said there should be 4,981. I also was able to produce a dump with `xml = xml.replace('</revision>\n</mediawiki>', '</revision>\n  </page>\n</mediawiki>')`, and that had 3745 revisions (probably due to a later edit).

Note that this wiki also detects index.php as `http://wiki.calafou.org/index.php`, not <code>http<ins>s</ins>://wiki.calafou.org/index.php</code>. But the http version redirects to the https one. This redirects converts POST into GET (I think), which for Python 2 WikiTeam tools produces `ATTENTION: This wiki does not allow some parameters in Special:Export, therefore pages with large histories may be truncated`. Manually using `--index` and `--api` solves that.
